import { test, expect } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';

// Live site under test. Override with SITE_URL; defaults to the Vercel deployment.
const SITE_URL = process.env.SITE_URL || 'https://leonistic.vercel.app';

// Supabase creds come from .env (loaded by playwright.config.ts via `import 'dotenv/config'`).
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

// All addresses generated by this test share this prefix, so we can find and
// remove only test-created rows during teardown.
const TEST_EMAIL_PREFIX = 'playwright-test+';

// Teardown: delete every test-created signup. Runs after the test has already
// verified the row, so the assertions are the proof — this just cleans up.
// Using a pattern match also sweeps any leftover rows from earlier runs.
test.afterAll(async () => {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) return;

  const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  const { data, error } = await supabase
    .from('signups')
    .delete()
    .like('email', `${TEST_EMAIL_PREFIX}%@example.com`)
    .select('id');

  if (error) {
    console.warn(`⚠ Teardown could not delete test rows: ${error.message}`);
  } else {
    console.log(`✓ Teardown removed ${data?.length ?? 0} test row(s) from Supabase`);
  }
});

test('contact form submits and persists to Supabase', async ({ page }) => {
  // Unique email so reruns never collide and we can find this exact row later.
  const email = `playwright-test+${Date.now()}@example.com`;
  const name = 'Playwright Test User';
  const message = 'This is an automated test submission';

  await test.step('Open the live site and scroll to the contact form', async () => {
    await page.goto(SITE_URL, { waitUntil: 'domcontentloaded' });
    await page.locator('#contact').scrollIntoViewIfNeeded();
    await expect(page.locator('#contact-form')).toBeVisible();
  });

  await test.step('Fill out and submit the form', async () => {
    await page.fill('#cf-name', name);
    await page.fill('#cf-email', email);
    await page.fill('#cf-message', message);
    await page.click('#contact-form .btn-submit');
  });

  await test.step('Success message appears within 5 seconds', async () => {
    const status = page.locator('#form-status');
    await expect(status).toHaveClass(/ok/, { timeout: 5000 });
    await expect(status).toContainText('Thanks!', { timeout: 5000 });
    console.log(`✓ Form submitted — success message shown for ${email}`);
  });

  // Separate step: if this fails while the step above passed, the form "worked"
  // (UI success) but the row never reached the database.
  await test.step('Verify the row was created in Supabase', async () => {
    expect(
      SUPABASE_URL && SUPABASE_ANON_KEY,
      'SUPABASE_URL and SUPABASE_ANON_KEY must be set in .env'
    ).toBeTruthy();

    const supabase = createClient(SUPABASE_URL!, SUPABASE_ANON_KEY!);
    const { data, error } = await supabase
      .from('signups')
      .select('id, name, email, message, created_at')
      .eq('email', email)
      .limit(1);

    expect(error, error?.message).toBeNull();
    expect(data, 'expected exactly one signup row for this email').toHaveLength(1);

    const row = data![0];
    expect(row.name).toBe(name);
    expect(row.message).toBe(message);
    console.log(`✓ Supabase row verified — id=${row.id}, created_at=${row.created_at}`);
  });
});
